### ISSUE TITLE
Question: How to add helpers?

### ISSUE THREAD

**Issue by pmochine** [melihovv/laravel-package-generator#8]
In my composer.json I have written:

    "autoload": {
        "psr-4": {
          "Pmochine\\MyOwnPackage\\": "src/"
        },
        "files": [
          "src/helpers.php"
        ]
      },

But somehow even after composer dump-autoload the functions are not loaded. I get "Call to undefined function".  Maybe it has something to do that it creates a symlink in the vendor folder? 

Inside helpers I have written

    <?php

    if (! function_exists('myowntest')) {

       function myowntest()
       { 
          return 'test'; 
       }
    }

My only way to use it is currently in the serviceprovider

   ```
public function boot()
    {
        $this->publishes([
            self::CONFIG_PATH => config_path('localization.php'),
        ], 'config');

        //Delete in future time
        if (file_exists($file = __DIR__.'/helpers.php')) { 
            require $file;
        }
    }
```

**Comment by melihovv** [comment]
Instead of `composer dump-autoload` try `composer update you/your-package`.

**Comment by melihovv** [comment]
More info here https://github.com/composer/composer/issues/5520
